spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false # This setting will stop the gateway from automatically discovering routes based on the services registered with the service registry. we use this false when we make the apis of microservices in LowerCase so we need to prevent the call of UpperCase
          lowerCaseServiceId: true   # this line makes microservices APIs access in lowercase


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Eazy Bank Gateway server application"
    version: "1.0.0"

logging:
  level:
    com:
      eazybytes:
        gatewayserver: DEBUG
